package reference;

public enum JBombRequestResponse {
	GAME_LIST_REQUEST,
	GAME_LIST_RESPONSE,
	GAMES_INFORMATION_REQUEST,
	GAMES_INFORMATION_RESPONSE,
	JOIN_GAME_REQUEST,
	JOIN_GAME_RESPONSE,
	GAMEPLAY_INFORMATION_REQUEST,
	GAMEPLAY_INFORMATION_RESPONSE,
	BOMB_OWNER_REQUEST,
	BOMB_OWNER_RESPONSE,
	QUIZ_ANSWER_REQUEST,
	QUIZ_ANSWER_RESPONSE,
	QUIZ_QUESTION_REQUEST,
	QUIZ_QUESTION_RESPONSE,
	CHANGE_BOMB_OWNER_REQUEST,
	CHANGE_BOMB_OWNER_RESPONSE,
	BOMB_DETONATED_REQUEST,
	BOMB_DETONATED_RESPONSE,
	
}