package reference;

public enum JBombRequestResponse {
	ERROR_FLASH,
	NOTICE_FLASH,
	
	GAME_LIST_REQUEST,
	GAME_LIST_RESPONSE,
	JOIN_GAME_REQUEST,
	GAMEPLAY_INFORMATION_RESPONSE,
	PLAYER_ADDED,
	BOMB_OWNER_RESPONSE,
	CHANGE_BOMB_OWNER_REQUEST,
	QUIZ_QUESTION_RESPONSE,
	QUIZ_ANSWER_REQUEST,
	GAMEPLAY_STATE_RESPONSE,
	BOMB_DETONATED_RESPONSE,

	FINISH_CONNECTION_REQUEST
}